sources:
  - name: rest
    handler:
      openapi:
        source: https://raw.githubusercontent.com/yoshino/graphql_mesh_gateway/main/rest_api/open_api.yaml
  - name: graphql
    handler:
      graphql:
        endpoint: http://172.16.238.4:3000/graphql
